# Generated by Django 3.0.2 on 2020-01-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apka', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='data_premiery',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='film',
            name='opis',
            field=models.TextField(default=''),
        ),
    ]
