# Generated by Django 3.0.2 on 2020-01-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apka', '0002_auto_20200114_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='tytul',
            field=models.CharField(max_length=128),
        ),
    ]
