# Generated by Django 3.0.2 on 2020-01-14 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apka', '0006_film_dlugosc'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='plakat',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
