# Generated by Django 3.0.2 on 2020-01-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='plakat',
            field=models.ImageField(default=None, upload_to='plakaty'),
        ),
    ]
